name: flutter_sodium_example
version: 2.0.0
description: Demonstrates how to use the flutter_sodium plugin.
publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sodium:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - lib/samples.dart
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf